name: Compile a cerebellum

on:
  schedule:
    - cron: "* 23 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies & self
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Run integration tests
      run: |
        echo "Disabled integration testing as it deadlocks and uses up GHA quota"
#        CEREB_INTEGRATION_TESTING=ON python -m unittest
